/**
 * Book access for reading exercises.
 *
 * Epubs are served same-origin from public/books/ (copied from repo books/ via
 * npm run copy:books). This avoids Firebase Storage browser CORS entirely.
 *
 * Upload scripts (scripts/upload-books.sh) can still push books to Storage for
 * backup; the running app reads from public/books/ bundled with Hosting.
 */

export const BOOKS_PATH = 'books';

export interface BookInfo {
  id: string;
  title: string;
  path: string;
}

const EPUB_EXTENSION = '.epub';

const publicBase = (): string => process.env.PUBLIC_URL || '';

const bookUrl = (bookId: string): string =>
  `${publicBase()}/books/${bookId}${EPUB_EXTENSION}`;

const manifestUrl = (): string => `${publicBase()}/books/manifest.json`;

/**
 * List books from public/books/manifest.json (generated by scripts/sync-books-to-public.js).
 */
export const listBooks = async (): Promise<BookInfo[]> => {
  const response = await fetch(manifestUrl());
  if (!response.ok) {
    throw new Error(
      'Books manifest not found. Run: npm run copy:books (copies books/*.epub into public/books/).'
    );
  }
  const entries: Array<{ id: string; title: string }> = await response.json();
  return entries.map((entry) => ({
    id: entry.id,
    title: entry.title,
    path: `${BOOKS_PATH}/${entry.id}${EPUB_EXTENSION}`,
  }));
};

/**
 * Download a book from same-origin public/books/ (no Storage, no CORS).
 */
export const downloadBook = async (bookId: string): Promise<ArrayBuffer> => {
  const response = await fetch(bookUrl(bookId));
  if (!response.ok) {
    throw new Error(
      `Book "${bookId}" not found at /books/${bookId}.epub. Run: npm run copy:books`
    );
  }
  return response.arrayBuffer();
};
